# Generated by Django 2.1.4 on 2018-12-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cipher',
            old_name='translaction',
            new_name='displacement',
        ),
    ]
